version: '3.8'
services:
  app:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
      - node_modules:/workspace/frontend/node_modules
      - synthea_output:/workspace/app/services/medical/synthea/output
    environment:
      - PYTHONUNBUFFERED=1
      - JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
      - NODE_ENV=development
    ports:
      - "5000:5000"  # For Flask API
      - "8000:8000"  # For FastAPI
      - "5173:5173"  # For Vite dev server
    working_dir: /workspace
    command: sleep infinity

volumes:
  synthea_output:
  node_modules: